/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconIcBaseline3dRotation: typeof import('~icons/ic/baseline3d-rotation')['default']
    IconIcBaseline5g: typeof import('~icons/ic/baseline5g')['default']
    IconIcBaselineAirplanemodeActive: typeof import('~icons/ic/baseline-airplanemode-active')['default']
    IconVcClean: typeof import('~icons/vc/clean')['default']
    IconVcClose: typeof import('~icons/vc/close')['default']
    IconVcMax: typeof import('~icons/vc/max')['default']
    IconVcMin: typeof import('~icons/vc/min')['default']
    IconVcPoint: typeof import('~icons/vc/point')['default']
    IconVcPolygon: typeof import('~icons/vc/polygon')['default']
    IconVcPolyline: typeof import('~icons/vc/polyline')['default']
    IconVcToolbox: typeof import('~icons/vc/toolbox')['default']
  }
}
